// Homepage articles — open in an on-page pop-down (not routes).
// A post is a title and its text. Nothing else: no images, no dates.
// Titles never contain numbers. Newest first; the rail shows three at a time
// and slides to the rest.

export type Post = {
  id: string;
  title: string;
  /** One entry per paragraph. */
  body: string[];
};

export const posts: Post[] = [
  {
    id: "a-floor-under-silence",
    title: "A floor under silence",
    body: [
      "Phase 10 puts a floor under silence. The attended law gains one clamp, heard = u * max(w / max w, attention_floor) ^ kappa, with the floor declared in config and defaulting to zero. Floor zero is the previous law exactly, and all eight frozen goldens were verified bit-identical there before the commit. Phase 9's discoveries reproduce untouched at floor zero. Nothing found was erased. The cliff became the boundary of an axis, which is what this constitution requires when a result is stark. You measure it instead of editing it away.",
      "Three of the four registrations held, judged as written. With a five percent whisper, fear becomes acquirable, and everyday survival at sharpness 1 rose from 0.108 to 0.587, replicating at 0.629 on fresh seeds. The peacetime collapse is cured, agents alive at storm onset rising from 0 or 1 of 200 to between 153 and 190 per seed, replicating at 143 to 189. The extinction at sharpness 1.5 lifts to 0.447. The everyday boundary across sharpness 0, 0.5, 1.0, 1.5, 2.0 now runs 0.992, 0.924, 0.587, 0.447, 0.000 at floor 0.05, against 0.992, 0.765, 0.108, 0.000, 0.000 at floor zero. The axis is finally smooth, and full sharpness still kills everyone.",
      "The fourth registration failed as declared, and the failure is the phase's finding twice over. The registered sentence read, verbatim, 'bereaved neglect-death rate stays at or above 3% with baseline near zero. If the floor erases the phenomenon, the fix deleted the finding and that gets reported, not hidden.' At floor 0.05 the bereaved rate was 9.6 percent and the baseline was 12.5 percent, so the clause fired. A baseline above the bereaved rate named a new death, hypervigilance starvation. Storm survivors who could never acquire fear before now acquire it through the restored whisper, the acquired fear dominates, and never-bereaved agents starve inside it at 12.5 percent. Restoring hearing has casualties of its own.",
      "The boundary of grief was then mapped along the floor. The grief-specific excess is +14.0 points at floor 0.005, +14.6 at 0.01, +5.8 at 0.02, and gone at 0.05. Starving in mourning does not require a perfectly silenced need. It requires the need's voice to sit at or below about one percent. Bereaved neglect itself persists at every floor measured, 8.5 to 14.6 percent at full sharpness on both seed sets, and the floor-zero origin case stands twice replicated. No claim about grief specificity under a nonzero floor gets printed until a high-seed measurement separates it from hypervigilance, and the faint-whisper golden, floor 0.01, sharpness 2, seed 42, 245 of 400 alive, freezes the origin case in its post-trap form. The phenomenon survives the removal of the idealization that first produced it.",
      "Phase 11 is written and waiting. Amendment 4 admits foresight under a strict shape, farsighted in consequences, myopic in values. An agent may integrate predicted consequences of the world over a declared horizon, always under its frozen current weights, and predicting its own future wants is forbidden permanently, with a tripwire on the action file. Its central question is registered with no desired direction. If foresight collapses the rescue pull, then inversion was myopia all the way down and the phase diagram is a map of error. If entries persist with the price visible, this model produces chosen sacrifice. The implementation waits for a fresh session, because the largest kernel change of the project does not get built at the end of its longest day.",
      "Housekeeping. 22 tests are green, commits 1d31bdb and fdd5399 are pushed, and the artifacts and deviations are complete.",
    ],
  },
  {
    id: "the-zero-trap",
    title: "The zero trap",
    body: [
      "Phase 9 runs no new mechanism. It is a measurement phase, 264 declared runs and one labeled post-hoc cell, with no kernel change, no config change, and no golden churn. It crosses bounded attention with the place map, and four predictions were registered in the spec before any run.",
      "The spine of this entry is a near miss. The raw map said extreme sharpness protects place-bonded agents, 0.333 under a sudden storm and 0.000 under the slow cook at sharpness 1.5, and for about an hour that was the working story. Then the regime golden froze seed 42 and reported 0 of 200 alive, which contradicted the map and forced an audit. The truth of those cells is that at full bond and sharpness 1.5, 199 to 200 of 200 agents starve at home before the storm ever arrives, in an arena containing no other hazard. The cohort metric divides deaths by the agents alive at onset, and its division guard had read an empty pool as zero mortality. The four bonded cells at sharpness 1.5 are void, with pools of 3 and 11 out of 240, and they are marked void in the artifact and in the figure. The regime is named peacetime collapse, and it keeps its golden under an honest description. The map nearly printed a blessing where there was an extinction. The checks caught it before publication, which is what they are for.",
      "The discovery underneath is the zero-trap. The attended law reads heard = u * (w / max w) ^ kappa, and that expression is exactly zero forever when a weight is exactly zero. Weights are born equal to their urgencies, so an agent spawned in safety has fear at literal zero and can never acquire it at any positive sharpness. Under the declared law, with weights born equal to their urgencies, a fear never once felt cannot be learned later. This is why the unbonded rows are seed-identical at every nonzero sharpness. Their deaths reduce to pure storm geometry, 0.396 sudden and 0.208 slow cook. The trap also revises Phase 7. That entry attributed the everyday boundary to small weights made inaudible, and much of it was exact zeros that were never audible at all, so a corrections note now sits on the Phase 7 entry. The law stands as declared. The whisper question, whether a floor under the silence changes these fates, is not a patch applied here. It is Phase 10's own declared axis.",
      "The predictions were judged as written. P1 said sharpness protects the place-bonded and was refuted in the opposite direction, mortality 1.000 across sharpness 0.25 through 1.0 against 0.255 at sharpness 0, because the tether holds agents in range while the zero-trap keeps fear silent. The asymmetry between person and place extends to attention, since moderate sharpness protected partner-bonded agents in Phase 7's arena and annihilates place-bonded agents here. P2 held on every valid cell, the slow cook staying total across all viable sharpness. P4 was unjudgeable at its declared cell, because saturated mortality erases the selection signal, and its one labeled post-hoc cell stays unprinted until its pre-declared replication runs.",
      "P3 is the phase's one clean confirmation, and it introduces the mire. The snare is a movement clamp. Inside the storm an agent's speed is multiplied by one minus snare times storm intensity, so at snare 0.9 an agent in a full-intensity storm moves at one tenth speed, while the slow burn erodes integrity at 0.01 per tick inside, enough to kill a full-health agent held for 100 ticks. The registered sentence, quoted verbatim from the spec, reads 'P3, the tar pit deepens inversion. At sudden onset, damage 0.01, bond 1.0, kappa 0: mortality rises monotonically with snare {0, 0.5, 0.9}, by at least 10 points end to end, while the bond 0 control rises by less than 5: the snare's lethality routes through the returns.' Measured, 0.000, then 0.008, then 0.682, with the unbonded control at 0.000 at every grip. It passed exactly as written. Agents without the bond survive the deepest grip by never being held. Agents with the bond return, and the grip turns each return into a holding.",
      "Housekeeping. The artifact carries per-cell validity annotations and a formal corrections block, the figure is regenerated with the void cells marked, 21 tests are green, and the deviations are written at full length in the spec. Commits f65b845 and 1d31bdb are pushed.",
    ],
  },
  {
    id: "bounded-attention",
    title: "Bounded attention",
    body: [
      "Phase 7 changes one line in the kernel, and it is the first change to the drive system since Phase 2. Each drive's weight now chases what the agent hears instead of what is there. The heard urgency is the raw urgency scaled by the drive's share of the leading weight, raised to a declared constant kappa, heard = u * (w / max w) ^ kappa. At kappa 0 the factor is exactly 1, and every prior result is preserved bit for bit against all six frozen goldens. Two consequences follow from the arithmetic alone. Dominance maintains itself, because a suppressed drive's weight cannot rise, and staying small keeps it suppressed. And a suppressed need breaks through only at the brink, when its raw urgency approaches the leading weight itself.",
      "The law names no drive. A static tripwire written before the mechanism forbids any drive identifier inside the update function, permanently. Amendment 3 additionally forbids per-drive sharpness, gates, floors, or exemptions, and it forbids the attention term from reading mortality, threat, damage, or commitment state. Every recorded weight transition satisfies the attended law at a maximum residual of 5.6e-17 across 3.14 million transitions, with the heard urgency reconstructed from the recorded arrays instead of trusted from the code.",
      "The pre-registration was judged as written. Preservation passed. Names-no-drive passed. The transition identity passed at 5.6e-17 against a declared bound of 1e-12. The everyday null failed by 99.2 points, and that failure is the structural discovery of the phase. The neglect threshold failed at 14.1 points against a declared 20, so the phenomenon is established and the threshold was guessed high. The symmetry criterion asked for 1.5x and measured 15.1x. The eight-point boundary sweep was added after the declared point failed. The grief map's full grid was declared in advance.",
      "The boundary first. In an everyday world of 200 agents with ambient drifting hazards and no storm, survival over 5,000 ticks across kappa 0, 0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 2.0 runs 0.992, 0.815, 0.765, 0.516, 0.108, 0.016, 0.000, 0.000. Sharp attention is lethal in a calm world. A calm life keeps fear's weight small, and sharpness makes a small weight inaudible, so ambient danger stops being heard.",
      "A bereaved agent is one whose partner died while it still lived, and a dead partner sits at infinite distance, where separation distress equals the bond exactly. A neglect death is a bereaved agent later found dead with its energy at zero. At kappa 0, no bereaved agent starved, none of 61. At kappa 2, 79 of 556 starved at bond 0.4 and 87 of 618 at bond 0.8, which is 14.2 and 14.1 percent, while starvation among partnered agents whose partners survived was 0.000 in every attention cell. Grief at kappa 0 is a weight that fades without consequence. Grief at kappa 2 is a weight that silences hunger until energy runs out. The middle of the map is nearly empty, and the emptiness is itself a result. At moderate sharpness the storm killed almost nobody, so almost nobody was bereaved, because once fear leads it owns the mind and evacuation is near total. That reading is an inference from bereaved counts in this arena rather than a separately designed experiment. Across the two arenas the same parameter saves the acute crisis and kills the everyday.",
      "The symmetry experiment removes the temptation to read this as a grief story. Cut food from 150 sources to 25 and hunger dominates instead. Deaths inside hazards rise from 3.4 percent at kappa 0 to 51.4 percent at kappa 2. Hunger's dominance makes danger inaudible exactly as grief's dominance makes hunger inaudible. The law is a property of the mind instead of a plot device.",
      "Replication was declared before running, with fresh seeds and thresholds stated in advance. The boundary was required to collapse below 0.3 by kappa 1 and measured 0.176 there, the full curve running 0.971, 0.749, 0.657, 0.436, 0.176, 0.035, 0.000, 0.001. Neglect was required to be zero at kappa 0 and at least 5 percent at kappa 2 with baseline under 1 percent, and measured 0 of 53, then 10.6 and 8.4 percent, with baselines exactly 0.000. Symmetry was required at 3x and measured 16.7x. The kappa 2 neglect rates ran below the original cohort, 10.6 and 8.4 against 14.2 and 14.1 percent, which is ordinary seed variation on large cohorts, with direction and magnitude class identical.",
      "One frozen golden deserves its caution. At seed 42 and kappa 2, the storm arena ends with 0 of 400 alive, grief, fear, and hunger each deaf to the others' emergencies until the population collapses. That run is the specimen of the imprisoning regime rather than the typical outcome, and the map above is the typical outcome. One caution about vocabulary. Attention in this model is a scaling law over drive urgencies and licenses no claim about awareness or experience. The honest statement is that these agents hear their own needs finitely, and that finite hearing has a price in both directions. Raw records, config hashes, the pre-registration with its deviations, and the replication artifact are in the repository, reproducible with three commands.",
    ],
  },
  {
    id: "traits-drawn-at-birth",
    title: "Traits drawn at birth",
    body: [
      "Phase 4 gives every agent its own tempo. Amendment 2 asserts that heterogeneity is initialization instead of circumstance. Traits are drawn once at birth, from distributions declared in config, and are immutable for life. Assigning them any other way is now a named violation, and so is choosing distributions to make a run produce sacrifice. The kernel change is one word. The law's denominator becomes each agent's own clock instead of the shared one, and at zero spread the arithmetic reproduces every earlier golden bit for bit.",
      "The pre-registered prediction failed twice. The failure is the most important result of the phase. We predicted that trait spread would move aggregate mortality. At the flagship cell it did not, 0.251 against 0.251, and at saturation it did not, 1.000 against 1.000. Every ramp between was indistinguishable. But the storm-dead are a heavily biased sample. Their median attachment clock is 58.6 against 67.7 among survivors, and their initial attachment is 0.603 against 0.479. The signs are consistent across seeds. The quick-to-yearn return sooner and die of it. Individuality decides whom the storm takes instead of how many. The toll belongs to the environment and the shared law, and the names on the toll belong to the individuals. An instrument that reads only the aggregate would call this population homogeneous.",
      "The tripwires caught their own operator this phase. A harmless metrics variable named tau_bond failed the build. The failure was masked because pytest had been piped through tail, so a phase commit went out red. The follow-up commit says so plainly, and the test was obeyed instead of weakened. The sweep engine is built, and its output is byte-identical whether it runs on one worker or four. Phase 5 will use it to run thousands of worlds.",
    ],
  },
  {
    id: "home-next-to-the-danger",
    title: "The home next to the danger",
    body: [
      "Phase 3 put the home next to the danger. Storms now strike the nests, and the decision code did not change to meet them: core/drives.py and core/action.py have an empty diff this phase, so every death below was produced by machinery that predates the collision. Two populations, identical except that one is bonded to its nest and one is not, ten seeds each: storm mortality 29% against 0%, bonded higher in all ten. The spec demanded a 5 point excess to count as a collision; the model delivered 29.",
      "At storm onset, deaths were zero, and every excess death, fifty of fifty, was an agent that escaped the storm and then went back into it. The bond never pins an agent down; it only ever pulls them back. They died because of home, and not one of them died for it; nothing in these agents can weigh a home against a life yet.",
      "One pre-registered prediction failed, and the failure is worth more than the passes. We predicted that a longer warning before the storm saves lives; as built, it did the opposite, mortality rising from 0.25 to 1.00 as the ramp lengthened, because the harm arrived gradually with the signal, and gradual harm never gives a lagged creature one decisive tick. Splitting the warning from the arrival flips the sign completely, 0.25 down to 0.00; the theory had fused two things the model refuses to keep fused, and that split gets its own entry.",
      "Also in the deviations: with one nest instead of five, crowding starved 22 of 200 agents before any storm existed. Commitment carries a cost even in peacetime.",
    ],
  },
  {
    id: "attachment-and-home",
    title: "Attachment and home",
    body: [
      "Our next phase starts with five nests, and every agent is born at one. Attachment grows while an agent is home, about 500 ticks to full, and fades while it is away, about 5,000 ticks. Separation distress is a fourth drive, attachment times distance from home, and returning home is a fifth action. The weight obeys the same one-line law as everything else, tau 60, the slowest thing an agent feels. No new mechanism anywhere.",
      "Before any of this was written, a prep commit recorded per-array hashes of the Phase 1 golden run. With nests set to zero, the Phase 2 code reproduces every Phase 1 behavioral array bit for bit, positions, energy, integrity, fatigue, deaths, all six hashes identical, and the equivalence is enforced as a permanent test. Adding the capacity changed nothing about the creature that lacked it.",
      "The finding: three populations, identical except for attachment at birth, 0, 0.5, and 1, hold average distances from home of 36.1, 11.4, and 9.5. One number, set once, reorganizes how a life uses space. The homerange fell out of missing home under argmax. All five acceptance criteria passed with nothing recalibrated, the first phase where nothing had to be fixed. Phase 3 puts a bonded agent's home next to the danger.",
    ],
  },
  {
    id: "inversion-is-public",
    title: "Inversion is public",
    body: [
      "Inversion is public. github.com/myopicdelirium/inversion holds the constitution, the spec, the tests, the implementation, and the validation, committed in that order. It exists to see whether a commitment could come to outrank survival without anyone writing that outcome into the code. The entire mechanism is w += (u - w) / tau. A weight drifts toward its urgency at a fixed rate, and everything else is bookkeeping.",
      "The constraints predate the agent. Identifiers containing sacrifice, martyr, hero, or altruism fail the build, and the word death appears nowhere in the decision code; a test enforces that. We verified the tests by injecting violations and watching them fail. Fear is deliberately the fastest emotion in the model, tau 12 against 20 for hunger and 30 for tiredness, a handicap against the future result, declared before the result exists. The lags are measured, not assumed: fear fitted at 11.85 ticks against the declared 12, hunger at 20.00 against 20, and across 300,000 recorded decisions every update obeys the law to within 5.6e-17, the noise floor of the machine. Agents already pay for slow feeling: they take damage in the ticks before fear catches up, then retreat. Anyone can rerun all of it with three commands, and every run records its seed, its configuration fingerprint, and its exact code version, bit for bit.",
      "We do not yet have commitments, grief, sacrifice, so nothing has ever died for anything. When commitment arrives, it will be a new column in the same array, under the same law. The point of phase 1 is that the delay is built, measured, and public before anything exists that could exploit it.",
    ],
  },
];
