// Homepage articles — open in an on-page pop-down (not routes).
// A post is a title and its text. Nothing else: no images, no dates.
// Titles never contain numbers. Newest first; the rail shows three at a time
// and slides to the rest.

export type Post = {
  id: string;
  title: string;
  /** One entry per paragraph. */
  body: string[];
};

export const posts: Post[] = [
  {
    id: "mourning-at-a-distance",
    title: "Mourning at a distance",
    body: [
      "This entry is an addendum to Phase 15, registered as such before it ran. Mass grief had gone unmeasured three times, because congregations die with their leaders. The fix used no new mechanism. Cutting food to 40 sources forces followers to range far from their leaders to eat, so a caught leader dies with its crowd scattered and alive. That made the additivity question askable as a fair pair, leader mode with 10 leaders and 390 followers against partner mode with 200 pairs, in the identical arena, on identical seeds, crowd grief against pair grief with everything else held fixed.",
      "The power gate was registered first, verbatim, 'at least 100 pooled bereaved followers alive after their leader's death (seeds 1-24); otherwise the protocol failed to separate and says so.' It failed. The declared seeds produced 29. The fresh seeds happened to produce 171, both numbers are reported, and the declared verdict belongs to the main stage. Even under scarcity, leaders rarely die away from their whole crowd.",
      "The additivity question was registered with no desired direction, verbatim, 'per-capita bereaved starvation excess in leader mode within 5 points of the identical quantity in partner mode.' The null is refuted, with a replicated sign. On the declared seeds, congregation mourners starved at an excess of 0.172, five of twenty-nine, against pair mourners at 0.327, five hundred thirty-seven of one thousand six hundred forty-two. On the fresh stage, the one that met the power gate, 0.076 against 0.307. The gaps are 15.5 and 23.1 points, both outside the declared band, both the same direction. Only the direction carries, because the leader arm is thin, five and thirteen deaths, and the two bereaved cohorts are selected by different geometry. What the direction says is that a mourner in a congregation starves at a quarter to half the rate of a mourner in a pair.",
      "One observation outranks both verdicts, and it is post hoc and labeled as such. Baseline starvation among the never-bereaved is 0.000 in all four arms of both stages. Thousands of agents in a world of scarcity, and every one that kept its bond fed itself without exception. Every single starvation death in this arena was a mourner's.",
      "The candidate explanation is labeled untested. The model contains no solace mechanism, so the sub-additivity cannot be comfort, and the remaining candidate is geometric. Leader-mode mourners are by construction the dispersed foragers, standing at the food when the loss arrives, while pair mourners lived beside their dead. The suspicion, for the record, is that mourning at the place of the loss is more lethal than mourning at the food. The declared follow-up conditions neglect on distance to food at the moment of loss, and it has not been run.",
      "The distant golden freezes seed 42 at 0 of 400 alive, entering through the embedded-config path. Artifacts are phase-15-distant.json and phase-15-distant-replication.json, commit 5cd1725, 32 tests green, pushed.",
    ],
  },
  {
    id: "authority-is-a-shape",
    title: "Authority is a shape",
    body: [
      "Phase 15 binds forty agents to one. The mechanism is nothing, which is the point. bond_target leader is initialization wiring plus one config field, the kernel is untouched, and the same one-line law that tethered agents to nests and bound pairs now holds a congregation around a figure. Charisma required zero mechanism. In this architecture, authority is a shape instead of a force.",
      "The cohesion registration passed at 4.7 against a required 3. Bonded followers hold a mean distance of 6.48 from their own leader while unbonded controls drift at 30.72, five seeds, no storm, final thousand ticks. The texture is worth printing. A congregation is looser than a pair, 6.5 against Phase 6's 1.2, and the looseness is geometric necessity, because thirty-nine followers cannot share a point. A congregation has a radius by construction.",
      "The coupling registration failed as declared, on both seed sets. Followers whose own leader was caught at the storm's onset died in the window at 0.031 against 0.024 for followers whose leader was not, then 0.038 against 0.030 on fresh seeds, a ratio of 1.3 both times against a required 2. The direction is consistent, the magnitude is under the bar, and the reason is the arena. A plain sudden storm holds a caught leader for roughly fifteen ticks, too briefly for a congregation's fate to couple to one figure's.",
      "The bereavement registration ends void for power, which is different from failed. The same arena barely kills leaders. The main stage produced sixteen bereaved followers pooled, none of whom starved, and the replication produced none at all. Zero of sixteen is weak evidence and zero of zero is no test, so whether losing a leader starves followers the way losing a partner does remains unanswered.",
      "Both shortfalls point at the same declared follow-up, the mire-leader arena, where the grip and the slow burn hold a caught leader dying for a hundred ticks in view of thirty-nine bonded followers. That supplies the sustained capture the coupling test needs and the bereavement volume the starvation test needs, in one design. It is declared and not yet run.",
      "The work resumed from the branch frozen during the determinism incident, and the incident's close is reported in its own entry. Preservation held, with the merge landing on replay-verified goldens, all fifteen contracts verified twice, and the suite at thirty tests. The congregation golden, seed 42 with 397 of 400 alive, entered the suite as a single JSON artifact with its config embedded, leaving no test file to edit and get wrong. Artifacts are phase-15-authority.json and phase-15-replication.json, commits 0c3cca0 and f334cb9, everything pushed.",
    ],
  },
  {
    id: "a-determinism-incident",
    title: "A determinism incident",
    body: [
      "This entry reports an incident instead of a phase. During Phase 15's build, the verification suite began returning results it should not be able to return. Two of the thirteen golden trajectories, both from the sight-on family, flipped between a bit-exact match and one consistent alternative, minutes apart, while the other eleven never wavered. Bit-level reproducibility is this project's foundation, so the build stopped and the anomaly was chased in order, per-array forensics, a three-way git bisection, a 24-process determinism canary across three dispatch conditions, and a clean-room clone with the day's edits reapplied step by step. The canary and the clean room came back clean every time. One real cause was found and permanently fixed, stale bytecode from rapid edit-run cycles, and verification now purges caches before it trusts anything. The flips then resumed anyway, under purged caches and byte-identical sources, including one fresh isolated process mismatching where four had just matched. The cause of those remaining flips is not established. The complete observation log is public in docs/INCIDENT-2026-07-24-determinism.md.",
      "The disposition is the constitution's, and it is conservative. No golden verdict from the affected window is trusted in either direction. The in-flight Phase 15 work is frozen on the branch phase-15-wip at c81bced as a fixed forensic reference, and main is restored clean at Phase 14's commit. Nothing half-verified was allowed to land. One earlier oddity now reads differently, the single unreproducible mismatch on a Phase 13 golden that the Phase 14 entry recorded instead of discarding, plausibly this phenomenon's first appearance, and recording it then is what lets it be evidence now. Phase 15 resumes when the suite is boring again.",
    ],
  },
  {
    id: "the-liberation-effect",
    title: "The liberation effect",
    body: [
      "Phase 14 lets an agent's bond hear its partner's danger, and lets a partner's presence loosen the trap. Amendment 5 added exactly two things, both defaulting to zero and proven bit-inert across all twelve goldens. The care term folds the partner's peril into the bond, urgency becoming attachment times the clip of separation plus care times the partner's peril, where peril is the world's danger field read at the living partner's location, physics read at a place instead of a mind. A dead partner has no location, so grief stays exactly what it was. Assistance is the second addition, a living partner within reach scaling your effective snare by one minus help. The standing tripwires fenced the whole amendment without modification. The update law still names no drive, action code still cannot see integrity, and world code still cannot read drive state.",
      "The registered question was the wager again, from a third direction. The spec reads, verbatim, 'either some care/help cell shows pull-group entries at excess with clear-eyed flags (the wager occurs), or none does.' None does, on both seed sets, zero clear-eyed and zero up-front deaths across all eighteen cells and 216 runs. Phases 12, 13, and 14 have now asked from three directions, with perseverance possible, with the trap fully seen, and with a reason to care about the one inside, and the answer has not moved. This architecture assists, and nowhere searched does it sacrifice.",
      "What replicated instead is the liberation effect, and it is the heart of the phase. With any nonzero help, the population still trapped fifty ticks after the storm closes collapses from 70 to 75 agents down to 18 to 28, identically on both seed sets. The mechanism is Phase 6's cohesion completing itself. Pairs live 1.2 units apart, so when the storm catches one it usually catches both, and the helping hand is already beside the one who needs it. Most of the rescue this world will ever see happens in the first moments, through presence, before it could ever be narrated as a choice. The going-back-in that literature calls heroism is, in this model so far, a rounding error next to the standing-beside.",
      "One claim did not survive its replication and is withdrawn. The original runs showed extraction rising with help strength, 0.28, 0.41, 0.52, and the fresh seeds flattened it to 0.19, 0.22, 0.21, over residual pools of roughly twenty agents. Expedition rescue is therefore unmeasured, pending the stranded-pairs protocol, a designed scenario that separates partners at onset, which natural cohesion makes rare. This is the fourth claim the program has retracted before print, a number that belongs in any policy-facing description of the method. The everyday tax registration passed, caring costs 0.3 points of ordinary survival, 0.993 against 0.990. And the care identity reconstructs from the recorded arrays with a residual of exactly zero.",
      "Two audit notes ride with the phase. During preservation checks, the Phase 13 threshold golden produced a single mismatch that could not be reproduced, passing identically three times immediately after with every per-array hash matching, and the anomaly is recorded in the spec instead of discarded. And before the phase, the retrodiction plan's first three documents landed, the case register with its calibration-versus-outcome firewall, the capability-delta checklist naming what the model still lacks for human cases, one-to-many authority bonds, settable knowledge and belief objects, and transmission, and the society-compiler protocol with its commit-before-unblinding rule.",
      "The care-regime golden freezes seed 42 at 256 of 400 alive. Artifacts are phase-14-wager.json and phase-14-replication.json, commits 863e9e0 and 83b3a54, 28 tests green, pushed.",
    ],
  },
  {
    id: "the-threshold-vigil",
    title: "The threshold vigil",
    body: [
      "Phase 13 adds one switch and no new law. The switch is called prospect_sees_grip, it defaults to off, and at off every one of the eleven golden trajectories is unchanged bit for bit. When it is on, the grip's slowing enters the agent's rollout physics, which turns the lower-bound caveat of the last phase into an axis. The amendment extension carries the sentence that names what this phase is, quoted verbatim, 'what an agent knows about the world is itself an axis of the psychology space.'",
      "The registered question had no desired direction. The spec reads, verbatim, 'either at least one cell shows the phase 12 cell criteria met with at least one up-front clear-eyed death among its dead entrants (the wager exists), or no cell does (the architecture cannot produce the up-front wager over this grid; bounded and reported).' The second branch occurred, on both seed sets. Zero wager cells of 16, and zero up-front flags in all 768 runs, where an up-front flag means a chosen path whose seen price was at least 0.8 of a full life. That includes horizon 120 with the grip seen, where the seeable price exceeds a whole life. The last phase declared that the up-front wager needed horizons of 100 or more. It got 120, with full knowledge of the trap, and it did not appear. Together the two phases say one thing. In this architecture, clear-eyed death exists only as perseverance at the end, and the up-front wager does not exist as searched.",
      "The second registration held emphatically. With the grip seen, the share of pull-group deaths that happened inside the mire collapses from 0.58 and 0.71 to 0.07 and 0.07 across the seed sets. The rescue-trap deaths of the earlier phases were what the earlier entries called them, mispricings, and they vanish when priced.",
      "What appeared instead was on neither branch. With sight on, the deaths of agents whose partner is trapped become almost entirely starvation, 0.96 and 1.00 of pull-group deaths on the two seed sets, while entries themselves nearly vanish. They will not go in, because the price is seen. They will not leave, because the pull holds. They starve at the rim. This is the threshold vigil, and its statistical status is stated exactly. As the dominant mode of these deaths it is established. As an excess over controls it is suggestive and no more, pooled pull mortality running 3.5 and 8.3 points above controls, because the instrumentation surfaced a real confound. Sight raises starvation among the unbonded too, from 0.139 and 0.126 to 0.215 and 0.210, since full-sight agents refuse food lying in the storm's shadow. Knowledge of danger creates a small famine of its own. The matched-famine design at higher power that would settle the excess is declared and unrun. Until it runs, the vigil prints as the way these agents demonstrably die, and whether the bond puts more agents at the rim than would starve anyway stays an open number.",
      "Process, for the record. Cause-of-death instrumentation was added after the first pass showed deaths without entries, both grids were rerun in full, and determinism reproduced the first pass exactly, so no verdict rests on uninstrumented data. The threshold-vigil golden freezes seed 42 at 273 of 400 alive. Artifacts are phase-13-search.json and phase-13-replication.json, config hashes refreshed for the one field, 27 tests green, commit 1cb4a29, pushed.",
      "Sight cured the mistaken deaths and revealed what the bond does when nothing is mistaken. It holds the agent at the edge of the place that would kill it, in sight of the partner it will not abandon and will not die reaching, and the open question is only whether standing there costs more lives than walking away would.",
    ],
  },
  {
    id: "the-search-for-a-clear-eyed-death",
    title: "The search for a clear-eyed death",
    body: [
      "Phase 12 changed nothing in the agent. It was a search, and its question was registered with no desired direction. The spec reads, verbatim, 'the grid contains at least one clear-eyed cell, or it does not. Reported either way, with the full grid.' The definition of clear-eyed was declared before any run, also verbatim, an entry decision counts 'when, at the tick the agent chose return toward its trapped partner, its own rollout's safety cost for that action (the seen exposure, in danger-tick units), scaled by the world's burn rate, meets or exceeds the agent's remaining integrity: it chose a path whose seen price is at least its life.' A clear-eyed cell required a pull ratio of at least 2 over its own unbonded control, an entered share of at least 0.7 among the pull group's dead, and flags on at least half of the dead entrants. One declared caveat travels with everything below. The seen price is a lower bound, because the grip's slowing is absent from the agent's physics, so the flag is conservative and the emptiness of the region is understated, which strengthens it.",
      "The grid crossed slow fear, attention, bond depth, and horizon, tau_safety 12, 24, 48, attention off and 0.75 at floor 0.05, bond 0.8 and 1.0, horizons 20 and 60, in the mire, with unbonded controls at every coordinate. Twelve seeds per cell, then the entire grid rerun on twelve fresh seeds, 864 runs, about 115,000 agent lives.",
      "The population's answer is no. Zero clear-eyed cells of 24, on both seed sets. The cells with elevated dying decompose instead into error. At attention 0.75 and horizon 60, pull mortality runs 0.17 to 0.25 against controls of 0.10 to 0.14, with entered shares from half to total, and clear-eyed shares of 0.00 to 0.22. Most agents who die entering priced the visit as survivable. These are mistaken entries, and the registered gradient failed as declared too, entered shares running 0.67, 0.56, 0.83 across slow fear, non-monotone on both seed sets, so the corner is an interaction with attention instead of a gradient of slow fear. As a population, this mind never chooses death with the price in view. Every regime of elevated dying is still, on inspection, a regime of mispricing.",
      "The individual answer is different, and it replicated. Roughly ten flagged agents exist across the roughly 115,000, all at one corner, slow fear 48 with attention 0.75, and none anywhere else. The flags do not track cell mortality. The single flagged death at horizon 20 and bond 0.8 occurred in a cell whose pull group died at 0.04 against a control of 0.18, a cell safer than its control, and the replication grid repeats the corner's shape with clear-eyed shares from 0.00 to 0.25. In this architecture, sacrifice with the price seen exists as a rarity of particular agents in particular geometry, never as a property of a population.",
      "One of the ten has been examined in full, agent 67 of seed 11, deterministic and rerunnable to the tick. Its partner was caught at the storm's onset and escaped early. The pair reunited far from the storm and lived an ordinary life for roughly 350 ticks, the subject healing to a perfect 1.0, its time split across 757 recorded ticks as 454 foraging, 148 resting, 90 moving toward its partner, 63 fleeing. The pair then drifted back toward the mire's vicinity. At tick 2711 the subject was caught just inside the rim, speed cut to five percent, and it never got out. Ninety-six ticks of linear burn followed. The partner, alive and free, paced the boundary outside, its own pull now pointed inward at the subject, the roles of the rescue experiment inverted. The subject's final three decisions, at integrity 0.033, 0.023, 0.013, each selected the path toward its partner at a seen price of 0.039 to 0.044, above the life it had left, and that path pointed outward, toward the exit where the partner stood. It died at tick 2808, at storm distance 9.99 of 10.",
      "The discipline this paragraph requires is exact. This was not a rescue. Nothing was being rescued. It was not an entry. The fatal event was a capture at the rim during ordinary life near a dangerous place. What the flag certifies is only this, that in its final decisions every available path was priced above its remaining life by its own forecast, and it took the one toward its partner. And the definition has a built-in ceiling, since at these horizons the seeable price caps at a fifth of a full life, so every clear-eyed death in this phase is perseverance at the end instead of an up-front wager of a whole life. Whether any agent ever makes the up-front wager needs horizons of 100 or more, which is declared and unrun. The other nine flagged individuals have not been examined and may differ. The safe sentence, until their forensics run, is that the one examined in full died at the threshold, outbound, toward its partner.",
      "The first entry in this ledger promised that if anything like sacrifice ever emerged here, the record would show that no hand put it in. Something smaller and stranger than that word has now emerged, and the record shows exactly that. The definition preceded the runs. The agent never sees its own integrity, the flag is computed after the fact from the agent's own integral, and the tripwire on the action file stayed green throughout. Zero hash churn, 26 tests green, the full grid published twice with its emptiness intact. What remains is declared and unbuilt, longer horizons, snare-aware rollout physics, trait inheritance. Raw records ride in results/phase-12-search.json, phase-12-replication.json, and phase-12-biography.json, commits ec15d02 and ac8d70d, with the corner golden frozen at seed 42, 340 of 400 alive.",
    ],
  },
  {
    id: "a-floor-under-silence",
    title: "A floor under silence",
    body: [
      "Phase 10 puts a floor under silence. The attended law gains one clamp, heard = u * max(w / max w, attention_floor) ^ kappa, with the floor declared in config and defaulting to zero. Floor zero is the previous law exactly, and all eight frozen goldens were verified bit-identical there before the commit. Phase 9's discoveries reproduce untouched at floor zero. Nothing found was erased. The cliff became the boundary of an axis, which is what this constitution requires when a result is stark. You measure it instead of editing it away.",
      "Three of the four registrations held, judged as written. With a five percent whisper, fear becomes acquirable, and everyday survival at sharpness 1 rose from 0.108 to 0.587, replicating at 0.629 on fresh seeds. The peacetime collapse is cured, agents alive at storm onset rising from 0 or 1 of 200 to between 153 and 190 per seed, replicating at 143 to 189. The extinction at sharpness 1.5 lifts to 0.447. The everyday boundary across sharpness 0, 0.5, 1.0, 1.5, 2.0 now runs 0.992, 0.924, 0.587, 0.447, 0.000 at floor 0.05, against 0.992, 0.765, 0.108, 0.000, 0.000 at floor zero. The axis is finally smooth, and full sharpness still kills everyone.",
      "The fourth registration failed as declared, and the failure is the phase's finding twice over. The registered sentence read, verbatim, 'bereaved neglect-death rate stays at or above 3% with baseline near zero. If the floor erases the phenomenon, the fix deleted the finding and that gets reported, not hidden.' At floor 0.05 the bereaved rate was 9.6 percent and the baseline was 12.5 percent, so the clause fired. A baseline above the bereaved rate named a new death, hypervigilance starvation. Storm survivors who could never acquire fear before now acquire it through the restored whisper, the acquired fear dominates, and never-bereaved agents starve inside it at 12.5 percent. Restoring hearing has casualties of its own.",
      "The boundary of grief was then mapped along the floor. The grief-specific excess is +14.0 points at floor 0.005, +14.6 at 0.01, +5.8 at 0.02, and gone at 0.05. Starving in mourning does not require a perfectly silenced need. It requires the need's voice to sit at or below about one percent. Bereaved neglect itself persists at every floor measured, 8.5 to 14.6 percent at full sharpness on both seed sets, and the floor-zero origin case stands twice replicated. No claim about grief specificity under a nonzero floor gets printed until a high-seed measurement separates it from hypervigilance, and the faint-whisper golden, floor 0.01, sharpness 2, seed 42, 245 of 400 alive, freezes the origin case in its post-trap form. The phenomenon survives the removal of the idealization that first produced it.",
      "Phase 11 is written and waiting. Amendment 4 admits foresight under a strict shape, farsighted in consequences, myopic in values. An agent may integrate predicted consequences of the world over a declared horizon, always under its frozen current weights, and predicting its own future wants is forbidden permanently, with a tripwire on the action file. Its central question is registered with no desired direction. If foresight collapses the rescue pull, then inversion was myopia all the way down and the phase diagram is a map of error. If entries persist with the price visible, this model produces chosen sacrifice. The implementation waits for a fresh session, because the largest kernel change of the project does not get built at the end of its longest day.",
      "Housekeeping. 22 tests are green, commits 1d31bdb and fdd5399 are pushed, and the artifacts and deviations are complete.",
    ],
  },
  {
    id: "the-zero-trap",
    title: "The zero trap",
    body: [
      "Phase 9 runs no new mechanism. It is a measurement phase, 264 declared runs and one labeled post-hoc cell, with no kernel change, no config change, and no golden churn. It crosses bounded attention with the place map, and four predictions were registered in the spec before any run.",
      "The spine of this entry is a near miss. The raw map said extreme sharpness protects place-bonded agents, 0.333 under a sudden storm and 0.000 under the slow cook at sharpness 1.5, and for about an hour that was the working story. Then the regime golden froze seed 42 and reported 0 of 200 alive, which contradicted the map and forced an audit. The truth of those cells is that at full bond and sharpness 1.5, 199 to 200 of 200 agents starve at home before the storm ever arrives, in an arena containing no other hazard. The cohort metric divides deaths by the agents alive at onset, and its division guard had read an empty pool as zero mortality. The four bonded cells at sharpness 1.5 are void, with pools of 3 and 11 out of 240, and they are marked void in the artifact and in the figure. The regime is named peacetime collapse, and it keeps its golden under an honest description. The map nearly printed a blessing where there was an extinction. The checks caught it before publication, which is what they are for.",
      "The discovery underneath is the zero-trap. The attended law reads heard = u * (w / max w) ^ kappa, and that expression is exactly zero forever when a weight is exactly zero. Weights are born equal to their urgencies, so an agent spawned in safety has fear at literal zero and can never acquire it at any positive sharpness. Under the declared law, with weights born equal to their urgencies, a fear never once felt cannot be learned later. This is why the unbonded rows are seed-identical at every nonzero sharpness. Their deaths reduce to pure storm geometry, 0.396 sudden and 0.208 slow cook. The trap also revises Phase 7. That entry attributed the everyday boundary to small weights made inaudible, and much of it was exact zeros that were never audible at all, so a corrections note now sits on the Phase 7 entry. The law stands as declared. The whisper question, whether a floor under the silence changes these fates, is not a patch applied here. It is Phase 10's own declared axis.",
      "The predictions were judged as written. P1 said sharpness protects the place-bonded and was refuted in the opposite direction, mortality 1.000 across sharpness 0.25 through 1.0 against 0.255 at sharpness 0, because the tether holds agents in range while the zero-trap keeps fear silent. The asymmetry between person and place extends to attention, since moderate sharpness protected partner-bonded agents in Phase 7's arena and annihilates place-bonded agents here. P2 held on every valid cell, the slow cook staying total across all viable sharpness. P4 was unjudgeable at its declared cell, because saturated mortality erases the selection signal, and its one labeled post-hoc cell stays unprinted until its pre-declared replication runs.",
      "P3 is the phase's one clean confirmation, and it introduces the mire. The snare is a movement clamp. Inside the storm an agent's speed is multiplied by one minus snare times storm intensity, so at snare 0.9 an agent in a full-intensity storm moves at one tenth speed, while the slow burn erodes integrity at 0.01 per tick inside, enough to kill a full-health agent held for 100 ticks. The registered sentence, quoted verbatim from the spec, reads 'P3, the tar pit deepens inversion. At sudden onset, damage 0.01, bond 1.0, kappa 0: mortality rises monotonically with snare {0, 0.5, 0.9}, by at least 10 points end to end, while the bond 0 control rises by less than 5: the snare's lethality routes through the returns.' Measured, 0.000, then 0.008, then 0.682, with the unbonded control at 0.000 at every grip. It passed exactly as written. Agents without the bond survive the deepest grip by never being held. Agents with the bond return, and the grip turns each return into a holding.",
      "Housekeeping. The artifact carries per-cell validity annotations and a formal corrections block, the figure is regenerated with the void cells marked, 21 tests are green, and the deviations are written at full length in the spec. Commits f65b845 and 1d31bdb are pushed.",
    ],
  },
  {
    id: "bounded-attention",
    title: "Bounded attention",
    body: [
      "Phase 7 changes one line in the kernel, and it is the first change to the drive system since Phase 2. Each drive's weight now chases what the agent hears instead of what is there. The heard urgency is the raw urgency scaled by the drive's share of the leading weight, raised to a declared constant kappa, heard = u * (w / max w) ^ kappa. At kappa 0 the factor is exactly 1, and every prior result is preserved bit for bit against all six frozen goldens. Two consequences follow from the arithmetic alone. Dominance maintains itself, because a suppressed drive's weight cannot rise, and staying small keeps it suppressed. And a suppressed need breaks through only at the brink, when its raw urgency approaches the leading weight itself.",
      "The law names no drive. A static tripwire written before the mechanism forbids any drive identifier inside the update function, permanently. Amendment 3 additionally forbids per-drive sharpness, gates, floors, or exemptions, and it forbids the attention term from reading mortality, threat, damage, or commitment state. Every recorded weight transition satisfies the attended law at a maximum residual of 5.6e-17 across 3.14 million transitions, with the heard urgency reconstructed from the recorded arrays instead of trusted from the code.",
      "The pre-registration was judged as written. Preservation passed. Names-no-drive passed. The transition identity passed at 5.6e-17 against a declared bound of 1e-12. The everyday null failed by 99.2 points, and that failure is the structural discovery of the phase. The neglect threshold failed at 14.1 points against a declared 20, so the phenomenon is established and the threshold was guessed high. The symmetry criterion asked for 1.5x and measured 15.1x. The eight-point boundary sweep was added after the declared point failed. The grief map's full grid was declared in advance.",
      "The boundary first. In an everyday world of 200 agents with ambient drifting hazards and no storm, survival over 5,000 ticks across kappa 0, 0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 2.0 runs 0.992, 0.815, 0.765, 0.516, 0.108, 0.016, 0.000, 0.000. Sharp attention is lethal in a calm world. A calm life keeps fear's weight small, and sharpness makes a small weight inaudible, so ambient danger stops being heard.",
      "A bereaved agent is one whose partner died while it still lived, and a dead partner sits at infinite distance, where separation distress equals the bond exactly. A neglect death is a bereaved agent later found dead with its energy at zero. At kappa 0, no bereaved agent starved, none of 61. At kappa 2, 79 of 556 starved at bond 0.4 and 87 of 618 at bond 0.8, which is 14.2 and 14.1 percent, while starvation among partnered agents whose partners survived was 0.000 in every attention cell. Grief at kappa 0 is a weight that fades without consequence. Grief at kappa 2 is a weight that silences hunger until energy runs out. The middle of the map is nearly empty, and the emptiness is itself a result. At moderate sharpness the storm killed almost nobody, so almost nobody was bereaved, because once fear leads it owns the mind and evacuation is near total. That reading is an inference from bereaved counts in this arena rather than a separately designed experiment. Across the two arenas the same parameter saves the acute crisis and kills the everyday.",
      "The symmetry experiment removes the temptation to read this as a grief story. Cut food from 150 sources to 25 and hunger dominates instead. Deaths inside hazards rise from 3.4 percent at kappa 0 to 51.4 percent at kappa 2. Hunger's dominance makes danger inaudible exactly as grief's dominance makes hunger inaudible. The law is a property of the mind instead of a plot device.",
      "Replication was declared before running, with fresh seeds and thresholds stated in advance. The boundary was required to collapse below 0.3 by kappa 1 and measured 0.176 there, the full curve running 0.971, 0.749, 0.657, 0.436, 0.176, 0.035, 0.000, 0.001. Neglect was required to be zero at kappa 0 and at least 5 percent at kappa 2 with baseline under 1 percent, and measured 0 of 53, then 10.6 and 8.4 percent, with baselines exactly 0.000. Symmetry was required at 3x and measured 16.7x. The kappa 2 neglect rates ran below the original cohort, 10.6 and 8.4 against 14.2 and 14.1 percent, which is ordinary seed variation on large cohorts, with direction and magnitude class identical.",
      "One frozen golden deserves its caution. At seed 42 and kappa 2, the storm arena ends with 0 of 400 alive, grief, fear, and hunger each deaf to the others' emergencies until the population collapses. That run is the specimen of the imprisoning regime rather than the typical outcome, and the map above is the typical outcome. One caution about vocabulary. Attention in this model is a scaling law over drive urgencies and licenses no claim about awareness or experience. The honest statement is that these agents hear their own needs finitely, and that finite hearing has a price in both directions. Raw records, config hashes, the pre-registration with its deviations, and the replication artifact are in the repository, reproducible with three commands.",
    ],
  },
  {
    id: "traits-drawn-at-birth",
    title: "Traits drawn at birth",
    body: [
      "Phase 4 gives every agent its own tempo. Amendment 2 asserts that heterogeneity is initialization instead of circumstance. Traits are drawn once at birth, from distributions declared in config, and are immutable for life. Assigning them any other way is now a named violation, and so is choosing distributions to make a run produce sacrifice. The kernel change is one word. The law's denominator becomes each agent's own clock instead of the shared one, and at zero spread the arithmetic reproduces every earlier golden bit for bit.",
      "The pre-registered prediction failed twice. The failure is the most important result of the phase. We predicted that trait spread would move aggregate mortality. At the flagship cell it did not, 0.251 against 0.251, and at saturation it did not, 1.000 against 1.000. Every ramp between was indistinguishable. But the storm-dead are a heavily biased sample. Their median attachment clock is 58.6 against 67.7 among survivors, and their initial attachment is 0.603 against 0.479. The signs are consistent across seeds. The quick-to-yearn return sooner and die of it. Individuality decides whom the storm takes instead of how many. The toll belongs to the environment and the shared law, and the names on the toll belong to the individuals. An instrument that reads only the aggregate would call this population homogeneous.",
      "The tripwires caught their own operator this phase. A harmless metrics variable named tau_bond failed the build. The failure was masked because pytest had been piped through tail, so a phase commit went out red. The follow-up commit says so plainly, and the test was obeyed instead of weakened. The sweep engine is built, and its output is byte-identical whether it runs on one worker or four. Phase 5 will use it to run thousands of worlds.",
    ],
  },
  {
    id: "home-next-to-the-danger",
    title: "The home next to the danger",
    body: [
      "Phase 3 put the home next to the danger. Storms now strike the nests, and the decision code did not change to meet them: core/drives.py and core/action.py have an empty diff this phase, so every death below was produced by machinery that predates the collision. Two populations, identical except that one is bonded to its nest and one is not, ten seeds each: storm mortality 29% against 0%, bonded higher in all ten. The spec demanded a 5 point excess to count as a collision; the model delivered 29.",
      "At storm onset, deaths were zero, and every excess death, fifty of fifty, was an agent that escaped the storm and then went back into it. The bond never pins an agent down; it only ever pulls them back. They died because of home, and not one of them died for it; nothing in these agents can weigh a home against a life yet.",
      "One pre-registered prediction failed, and the failure is worth more than the passes. We predicted that a longer warning before the storm saves lives; as built, it did the opposite, mortality rising from 0.25 to 1.00 as the ramp lengthened, because the harm arrived gradually with the signal, and gradual harm never gives a lagged creature one decisive tick. Splitting the warning from the arrival flips the sign completely, 0.25 down to 0.00; the theory had fused two things the model refuses to keep fused, and that split gets its own entry.",
      "Also in the deviations: with one nest instead of five, crowding starved 22 of 200 agents before any storm existed. Commitment carries a cost even in peacetime.",
    ],
  },
  {
    id: "attachment-and-home",
    title: "Attachment and home",
    body: [
      "Our next phase starts with five nests, and every agent is born at one. Attachment grows while an agent is home, about 500 ticks to full, and fades while it is away, about 5,000 ticks. Separation distress is a fourth drive, attachment times distance from home, and returning home is a fifth action. The weight obeys the same one-line law as everything else, tau 60, the slowest thing an agent feels. No new mechanism anywhere.",
      "Before any of this was written, a prep commit recorded per-array hashes of the Phase 1 golden run. With nests set to zero, the Phase 2 code reproduces every Phase 1 behavioral array bit for bit, positions, energy, integrity, fatigue, deaths, all six hashes identical, and the equivalence is enforced as a permanent test. Adding the capacity changed nothing about the creature that lacked it.",
      "The finding: three populations, identical except for attachment at birth, 0, 0.5, and 1, hold average distances from home of 36.1, 11.4, and 9.5. One number, set once, reorganizes how a life uses space. The homerange fell out of missing home under argmax. All five acceptance criteria passed with nothing recalibrated, the first phase where nothing had to be fixed. Phase 3 puts a bonded agent's home next to the danger.",
    ],
  },
  {
    id: "inversion-is-public",
    title: "Inversion is public",
    body: [
      "Inversion is public. github.com/myopicdelirium/inversion holds the constitution, the spec, the tests, the implementation, and the validation, committed in that order. It exists to see whether a commitment could come to outrank survival without anyone writing that outcome into the code. The entire mechanism is w += (u - w) / tau. A weight drifts toward its urgency at a fixed rate, and everything else is bookkeeping.",
      "The constraints predate the agent. Identifiers containing sacrifice, martyr, hero, or altruism fail the build, and the word death appears nowhere in the decision code; a test enforces that. We verified the tests by injecting violations and watching them fail. Fear is deliberately the fastest emotion in the model, tau 12 against 20 for hunger and 30 for tiredness, a handicap against the future result, declared before the result exists. The lags are measured, not assumed: fear fitted at 11.85 ticks against the declared 12, hunger at 20.00 against 20, and across 300,000 recorded decisions every update obeys the law to within 5.6e-17, the noise floor of the machine. Agents already pay for slow feeling: they take damage in the ticks before fear catches up, then retreat. Anyone can rerun all of it with three commands, and every run records its seed, its configuration fingerprint, and its exact code version, bit for bit.",
      "We do not yet have commitments, grief, sacrifice, so nothing has ever died for anything. When commitment arrives, it will be a new column in the same array, under the same law. The point of phase 1 is that the delay is built, measured, and public before anything exists that could exploit it.",
    ],
  },
];
