import type { CopenWienArticle } from "./types"

const article: CopenWienArticle = {
  slug: "honest-display-credence-public-composure",
  title: "Honest display, credence, and public composure",
  abstract:
    "A pre-registered agent-based study of warning credibility, following, and the group-size vigilance effect, run where an agent's display is a read-only view of its own urgency and the effect can be measured within individuals rather than across them.",
  authors: ["Felix Tinio", "Giulia Apolloni", "Bruno Risach", "Jacob Daaboul"],
  keywords: [
    "agent-based simulation",
    "bounded attention",
    "warning credibility",
    "vigilance and group size",
    "honest signalling",
    "pre-registered prediction",
  ],
  status: "Extended abstract",
  year: "2026",
  body: [
    {
      text: "Two observations recur in the literature on vigilance and warning. The first is that individuals in company scan less than solitary individuals. Pulliam's 1973 model predicts the decline of individual vigilance with group size, which has been seriously contested since. Elgar's 1989 review of more than fifty bird and mammal studies evaluated the strength of the published conclusions and set out the variables capable of confounding the relationship, assessing their control study by study, among them food density, competition between individuals, proximity to cover, visibility, and the composition of the group. Beauchamp's 2008 meta-analysis of the bird literature found weak to moderate negative correlations, reported that nearly a third of published relationships were not statistically significant, and found the effect stronger in studies that controlled the food available. A 2021 meta-analysis of mammals found 43 percent of effect sizes compatible with a null or positive effect and traced part of the remaining variation to how vigilance had been quantified. The critique that persists across all of it is that these comparisons are cross-sectional. Larger groups form in different places and out of different individuals, so a lower group mean may report who is in the group instead of what the group does to its members.",
    },
    {
      text: "The second observation is that attention shifts with the accuracy of what a signaler conveys. Breznitz showed in laboratory work with threatened and then cancelled shocks that each false alarm cost credibility, and that a more frightening initial alarm cost more of it once revealed as false. Work in cultural evolution finds deference flowing toward indicated skill instead of toward held position (Henrich and Gil-White 2001). The applied evidence is more equivocal than the metaphor suggests. Dow and Cutter studied two 1996 hurricanes forecast for South Carolina that struck North Carolina instead, and found that residents doubted the reliability of official warnings while declining to describe officials as crying wolf, turning to media sources to judge whether the risk applied to them personally. LeClerc and Joslyn reported the first controlled experimental evidence of the effect, of moderate size, alongside two results that complicate it, since very high and very low false-alarm rates both degraded decision quality while a modest reduction in the rate changed neither compliance nor decision quality. Whether inaccuracy erodes attention, and along what curve, is open, but both literatures face one obstacle. Displayed states can be regulated, and where display rules govern expression (Ekman and Friesen 1969) and conduct before others is managed (Goffman 1959), a drop in public arousal admits two readings. The decisive comparison is within-individual under matched conditions. This phase runs in the Inversion architecture, an agent-based model whose prior phases, registrations, and failures are available, and what an agent broadcasts there is a read-only view of its own urgency vector, enforced by a static test over the source code, so display regulation is structurally impossible.",
    },
    {
      text: "Our reformed model includes a display as a read-only broadcast of an agent's urgency vector covering danger, need, and fatigue, tripwired at build time so no path in the code can alter what is shown. It also includes credence, with each agent holding a bounded ledger of up to 16 known others, nearest first and stalest evicted, and for each one a single number in [floor, 1] obeying the same relaxation law as every other slow quantity in the model, c += (dt/tau_cred)(score - c), with tau_cred 24 drawn per agent from the same spread machinery as every other timescale. That number is trust for warnings, the gate for trade, and the substrate of affiliation at once. The model carries no separate reputation variable, so the cry-wolf effect, partner choice, and the follow gradient are forced to be one quantity measured three ways.",
    },
    {
      text: "Scoring is local and time-bounded. A display crossing 0.6 opens a 30-tick verification window for every listener in range, and at window close the alarm scores 1 if verified peril arrived and 0 otherwise, with that score entering credence through the lagged law. No rule in the model names warning fatigue. It is what the law does to a signaler whose alarms keep scoring 0, and it tracks the false-alarm fraction across the trailing credence window instead of a lifetime count of errors, with a half-life of ln2 times tau_cred, roughly 17 ticks at the declared value. A neighbor's danger display, multiplied by credence and by distance decay, enters the listener's safety urgency as evidence, where it competes with hunger and rest inside the same bounded attention field. Discounted warnings lose that competition rather than being filtered from it.",
    },
    {
      text: "The second channel is arithmetic instead of reputation. Speed, perception radius, and harm capability are drawn once at spawn from declared distributions and are immutable for life. Safety urgency is perceived peril scaled by the agent's own mitigation, a function of those stats, so the well-equipped feel less danger from the same hazard, display less, and change priorities less often. Following emerges from the same expected-relief accounting that selects every other action. An agent stands near whoever most reduces its rolled-forward urgencies, which makes a calm accurate neighbor worth holding position beside and a stressed inaccurate one costly, since every false flight interrupts foraging. Contests over food resolve by harm stats, losers take damage and flee, and an aggressor's violence is perceivable peril, so avoidance of the violent arrives through safety urgency without a reputation system. Trade is a transfer of surplus energy between adjacent agents whose mutual credence clears a threshold. The words stress, calm, and follower appear nowhere in decision code.",
    },
    {
      text: "Five definitions carry the measurements. The stress index is displayed safety urgency plus priority-flick rate over the trailing 50 ticks, standardized within run. Public means three or more neighbors within social range and private means fewer, so the same agent supplies observations of both kinds across its life. Follower in-degree is the count of agents whose affiliation currently targets the focal agent. A signaler's false-alarm fraction is the share of its alarms scoring zero across its trailing credence window, and a pariah is a signaler whose median credence among the agents that know it sits at the floor. Populations run along a declared hazard-rate axis from dangerous worlds to safe ones, crossed with attention sharpness at 0 and 2 and with the credence floor at 0 and 0.01. Reproduction is excluded and population size is fixed, so composition changes only through death and through where agents choose to stand.",
    },
    {
      text: "Three predictions concern credence. First, agents whose alarms verify will be followed at two to five times the rate of agents whose alarms do not, a range anchored on the topology effects this architecture has already produced, and a ratio below two fails. Second, discounting will track the recent false-alarm fraction instead of the lifetime error count. Matched signalers carrying equal lifetime error counts but differing recent rates should separate in follower in-degree by at least half the accurate-inaccurate gap, and a failure to separate would mean the lagged form does no work a running tally could not do. Third, the floor will divide two kinds of population. At floor zero a discredited signaler becomes structurally unhearable, and the pariah fraction should rise steeply once true alarms fall below roughly one per credence window. At floor 0.01 credence recovers and permanent pariahs should not appear. Forgiveness in this model is a declared parameter with a measurable consequence.",
    },
    {
      text: "Two predictions concern the follow gradient. In dangerous regimes the correlation between displayed stress and follower in-degree will be positive, Spearman between +0.2 and +0.4, because a stressed neighbor in a hazardous world is usually an accurate one and standing near it is informative. As the hazard rate falls the correlation will decline and change sign, and the crossing will occur near the point where a typical signaler's false-alarm fraction passes one half. A crossing far from that point, or no crossing at all, fails the prediction and would indicate that the reversal runs through capability rather than through accumulated inaccuracy. Magnitudes should roughly double at sharpness two against sharpness zero, since bounded attention concentrates following on fewer targets. The reversal reported in field settings would then be one correlation crossing zero as a single accuracy statistic moves, with no rule in the model naming stress, calm, or following.",
    },
    {
      text: "The final registration is the decomposition that opened this abstract, and it doubles as the phase's stop rule. Cross-sectionally, crowd members should show 30 to 60 percent lower mean stress index than solitary agents, the composition scale this architecture keeps producing. Within-agent, the same individual moving between private and public conditions, matched on local peril and energy state, should shift by less than five points of the standardized index. If both hold, public composure in these populations is a fact about who is in public instead of a fact about what public does to them. The bound is also a falsification. The display is read-only by construction and its tripwire runs on every build, so a replicated within-agent shift beyond the bound would mean the honesty guarantee has failed somewhere in the implementation. The phase stops, the anomaly takes an incident file, and nothing publishes until the cause is found.",
    },
    {
      text: "Every bar above will be judged as written, in each seed stage separately, on declared seeds and again on fresh ones, and both branches of every question report. The program behind these predictions has published fifteen phases under the same procedure, including withdrawn claims, one nominal pass refused because its premise had failed upstream, and one phenomenon filed open after two pre-registered attempts to explain it both failed.",
    },
  ],
}

export default article
