import type { Artifact } from "./types"

const a: Artifact = {
  slug: "terminal-commitment-emergent-martyrdom",
  title: "Terminal Commitment: Martyrdom and Self-Destruction as Emergent Properties of Cognitively-Grounded Agents",
  status: "Working paper",
  year: "2025",
  updated: "2025-11-18",
  authors: ["Felix Tinio"],
  keywords: ["ABM", "Martyrdom", "Self-destruction", "Inertial bands", "Attention", "Grief", "Durkheim", "Phase transition"],
  abstract: `Standard optimizing agents cannot die for a purpose. Death is an absorbing state of minimal value, so for every finite mission reward there exists a survival threshold at which a utility-maximizer always, eventually, drinks. Self-sacrifice must therefore be installed by hand with an unbounded weight on the cause, or a reward on dying, and the installation is always visible. We show that an architecture already rich enough to sustain long-horizon commitment produces self-destruction without any such installation. Agents carry persistence-gated motivation organized into inertial bands, a bounded attention budget for which physiological alarms must compete without a private channel, and affect-biased memory over an irreversible homeostatic base. When a mission object is lost, the search band latches and shields the thirst alarm below the threshold that triggers correction. Death arrives as a failure to re-prioritize, the point of no return crossed while the agent is, in effect, looking elsewhere. We distinguish valued from inertial martyrdom, develop a taxonomy of four dissociable death-regimes generated by one architecture (neglect, sacrifice, grief-collapse, anomic collapse), and map Durkheim's classical suicide typology onto a two-dimensional phase space spanned by integration and regulation. The central hazard result is structural, as an architecture cannot be granted the capacity for override-strength transcendent commitment while guaranteeing that capacity is never turned against survival, because they are the same mechanism at different thresholds. Ambition carries a death tail whose width is set by the parameters that set the depth of ordinary perseverance. A live instrument accompanies the paper, as we have developed a running population beside a phase diagram computed from the same update law (60-trial bereavement cohorts per cell), exhibiting a sharp boundary between release and martyrdom, closing a prediction-observation loop within a few percentage points, and demonstrating the two ablations: removing the inertial gate abolishes commitment and death together, granting the alarm a private channel preserves commitment while extinguishing death across the entire measured parameter plane. Faster affect decay is protective throughout. Rumination is the mechanism behind terminal grief.`,
  contactEmail: "myopicdelirium@gmail.com",
}

export default a
