export type Member = {
  name: string
  positions: string[]
  teams: string[]
  joined: string
  active: boolean
  school: string
}

export const members: Member[] = [
  {
    name: "Lena Marchetti",
    positions: ["Team Lead"],
    teams: ["ABBY"],
    joined: "2025-09",
    active: true,
    school: "UW",
  },
  {
    name: "Tomás Herrera",
    positions: ["Researcher"],
    teams: ["ABBY"],
    joined: "2025-10",
    active: true,
    school: "SIT",
  },
  {
    name: "Priya Chandrasekaran",
    positions: ["Researcher"],
    teams: ["ABBY", "EMMY"],
    joined: "2025-10",
    active: true,
    school: "KTH",
  },
  {
    name: "Idris Yilmaz",
    positions: ["Researcher"],
    teams: ["ABBY"],
    joined: "2025-11",
    active: true,
    school: "UW",
  },
  {
    name: "Clara Johansson",
    positions: ["Researcher"],
    teams: ["ABBY"],
    joined: "2026-01",
    active: false,
    school: "KTH",
  },
  {
    name: "Kai Nørgaard",
    positions: ["Team Lead"],
    teams: ["RODY"],
    joined: "2025-09",
    active: true,
    school: "SIT",
  },
  {
    name: "Anika Patel",
    positions: ["Researcher"],
    teams: ["RODY"],
    joined: "2025-10",
    active: true,
    school: "SIT",
  },
  {
    name: "Marcus Lindqvist",
    positions: ["Researcher"],
    teams: ["RODY", "HOBY"],
    joined: "2025-11",
    active: true,
    school: "KTH",
  },
  {
    name: "Sofia Reyes",
    positions: ["Researcher"],
    teams: ["RODY"],
    joined: "2025-12",
    active: true,
    school: "UW",
  },
  {
    name: "Daniel Okafor",
    positions: ["Researcher"],
    teams: ["RODY"],
    joined: "2026-01",
    active: false,
    school: "SIT",
  },
  {
    name: "Yuki Tanaka",
    positions: ["Team Lead"],
    teams: ["EMMY"],
    joined: "2025-09",
    active: true,
    school: "KI",
  },
  {
    name: "Elena Voronova",
    positions: ["Researcher"],
    teams: ["EMMY"],
    joined: "2025-10",
    active: true,
    school: "UW",
  },
  {
    name: "Rafael Costa",
    positions: ["Researcher"],
    teams: ["EMMY"],
    joined: "2025-11",
    active: true,
    school: "SIT",
  },
  {
    name: "Amara Diop",
    positions: ["Researcher"],
    teams: ["EMMY", "ABBY"],
    joined: "2025-11",
    active: true,
    school: "UW",
  },
  {
    name: "Henrik Strand",
    positions: ["Researcher"],
    teams: ["EMMY"],
    joined: "2026-01",
    active: true,
    school: "KTH",
  },
  {
    name: "Mika Saarinen",
    positions: ["Researcher"],
    teams: ["EMMY"],
    joined: "2026-02",
    active: true,
    school: "KI",
  },
  {
    name: "Jun Wei Chen",
    positions: ["Team Lead"],
    teams: ["HOBY"],
    joined: "2025-09",
    active: true,
    school: "KTH",
  },
  {
    name: "Nadia Kowalski",
    positions: ["Researcher"],
    teams: ["HOBY"],
    joined: "2025-10",
    active: true,
    school: "SIT",
  },
  {
    name: "Omar Benali",
    positions: ["Researcher"],
    teams: ["HOBY"],
    joined: "2025-11",
    active: true,
    school: "UW",
  },
  {
    name: "Ingrid Haugen",
    positions: ["Researcher"],
    teams: ["HOBY", "RODY"],
    joined: "2025-12",
    active: false,
    school: "KTH",
  },
  {
    name: "Leo Vasquez",
    positions: ["Researcher"],
    teams: ["HOBY"],
    joined: "2026-01",
    active: true,
    school: "SIT",
  },
]
